_BASE_: Base-BMask-R-CNN-FPN.yaml
MODEL:
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-50.pkl
  MASK_ON: true
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: CascadeBoundaryROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
INPUT:
  MIN_SIZE_TRAIN: (800,)
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "output/cascade_bmask_rcnn_r50_1x"